services:
  - type: web
    name: ml-workover-dashboard
    runtime: python
    pythonVersion: "3.11.4"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --timeout 600 --workers 1 --max-requests 10 --max-requests-jitter 3 --worker-class sync --preload